// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package translations

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
		"zh_CN": &dictionary{index: zh_CNIndex, data: zh_CNData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"Please login in":                3,
	"Websocket connect Closed":       1,
	"Websocket connect Successfully": 0,
	"更新成功":                           2,
}

var en_USIndex = []uint32{ // 5 elements
	0x00000000, 0x0000001f, 0x00000038, 0x00000045,
	0x00000055,
} // Size: 44 bytes

const en_USData string = "" + // Size: 85 bytes
	"\x02Websocket connect Successfully\x02Websocket connect Closed\x02更新成功" +
	"\x02Please login in"

var zh_CNIndex = []uint32{ // 5 elements
	0x00000000, 0x00000000, 0x00000000, 0x00000000,
	0x00000000,
} // Size: 44 bytes

const zh_CNData string = ""

// Total table size 173 bytes (0KiB); checksum: 1C18FC26
